spring:
  security:
    oauth2:
      client:
        registration:
          aad:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid,profile,email
        provider:
          aad:
            issuer-uri: https://login.microsoftonline.com/d032670a-3624-426a-b92d-61970bb22949/v2.0


server:
  port: 9091

logging:
  level:
    org:
      springframework: INFO
    com:
      simform: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"

